// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7BdSOpXlXSmHWlCC1LCXyt_a_S5T_sM',
    appId: '1:415251284478:ios:db4ffa92590491366980af',
    messagingSenderId: '415251284478',
    projectId: 'soup-photogrammetry-project',
    storageBucket: 'soup-photogrammetry-project.firebasestorage.app',
    iosClientId: '415251284478-g876kn2pdo0bg23j6oot6uqjdma28de2.apps.googleusercontent.com',
    iosBundleId: 'com.soup.scanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfz8HpSGV_FkpHpP6HhVnoqEvmgkNlDSA',
    appId: '1:415251284478:web:6b478ec716978f356980af',
    messagingSenderId: '415251284478',
    projectId: 'soup-photogrammetry-project',
    authDomain: 'soup-photogrammetry-project.firebaseapp.com',
    storageBucket: 'soup-photogrammetry-project.firebasestorage.app',
    measurementId: 'G-PV3SNHQY2X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7BdSOpXlXSmHWlCC1LCXyt_a_S5T_sM',
    appId: '1:415251284478:ios:f6bb51bedec2a24c6980af',
    messagingSenderId: '415251284478',
    projectId: 'soup-photogrammetry-project',
    storageBucket: 'soup-photogrammetry-project.firebasestorage.app',
    iosClientId: '415251284478-61ervvqpl72l92vg6kje6ablcu1so93q.apps.googleusercontent.com',
    iosBundleId: 'com.soup.frontend',
  );

}