name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up dependencies
        run: |
          git submodule update --init --recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
          cache: true

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Create mocks
        run: dart run build_runner build

      - name: Run tests with coverage
        run: flutter test --coverage
